module.exports = {
  GUEST_SIDES: ['bride', 'groom', 'mutual'],
  RSVP_STATUSES: ['pending', 'confirmed', 'declined', 'tentative'],
  MEAL_PREFERENCES: ['vegetarian', 'jain', 'vegan', 'non_vegetarian'],
  AGE_GROUPS: ['child', 'adult', 'senior'],
  PAYMENT_STATUSES: ['pending', 'partial', 'paid', 'overdue', 'cancelled'],
  PAYMENT_METHODS: ['cash', 'bank_transfer', 'upi', 'cheque', 'credit_card'],
  TASK_PRIORITIES: ['low', 'medium', 'high', 'urgent'],
  TASK_STATUSES: ['pending', 'in_progress', 'completed', 'cancelled'],
  ROOM_TYPES: ['single', 'double', 'suite', 'family', 'dormitory'],

  VENDOR_CATEGORIES: [
    'caterer',
    'decorator',
    'photographer',
    'videographer',
    'mehendi_artist',
    'makeup_artist',
    'dj',
    'band',
    'florist',
    'pandit',
    'tent_house',
    'lighting',
    'invitation',
    'jeweller',
    'choreographer',
    'transportation',
    'other'
  ],

  BUDGET_CATEGORIES: [
    'Venue',
    'Catering',
    'Decoration',
    'Photography & Videography',
    'Bridal Attire & Jewelry',
    'Groom Attire',
    'Makeup & Mehendi',
    'Music & Entertainment',
    'Invitations & Stationery',
    'Accommodation',
    'Transportation',
    'Gifts & Favors',
    'Pandit & Rituals',
    'Miscellaneous'
  ],
};
