export const VENDOR_CATEGORIES = [
  'caterer',
  'decorator',
  'photographer',
  'videographer',
  'mehendi_artist',
  'makeup_artist',
  'dj',
  'band',
  'florist',
  'pandit',
  'tent_house',
  'lighting',
  'invitation',
  'jeweller',
  'choreographer',
  'transportation',
  'other',
] as const;

export const EXPENSE_CATEGORIES = [
  'Venue',
  'Catering',
  'Photography & Videography',
  'Decoration',
  'Entertainment',
  'Attire & Beauty',
  'Invitations & Stationery',
  'Transportation',
  'Accommodation',
  'Jewellery',
  'Mehendi & Rituals',
  'Miscellaneous',
] as const;
