// Auto-generated Supabase types — hand-crafted to match migration schema.
// Do not edit this file directly; regenerate from migrations instead.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// ---------------------------------------------------------------------------
// DB Enums
// ---------------------------------------------------------------------------

export type DbGuestSide = 'bride' | 'groom' | 'mutual';
export type DbRsvpStatus = 'pending' | 'confirmed' | 'declined' | 'tentative';
export type DbMealPreference = 'vegetarian' | 'jain' | 'vegan' | 'non_vegetarian';
export type DbAgeGroup = 'child' | 'adult' | 'senior';
export type DbPaymentMethod = 'cash' | 'bank_transfer' | 'upi' | 'cheque' | 'credit_card';
export type DbTaskPriority = 'low' | 'medium' | 'high' | 'urgent';
export type DbTaskStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled';
export type DbRoomType =
  | 'Standard Room'
  | 'Deluxe Room'
  | 'Super Deluxe Room'
  | 'Premium Room'
  | 'Executive Room'
  | 'Club Room'
  | 'Junior Suite'
  | 'Suite'
  | 'Executive Suite'
  | 'Luxury Suite'
  | 'Presidential Suite'
  | (string & {});

export type DbVendorCategory =
  | 'caterer'
  | 'decorator'
  | 'photographer'
  | 'videographer'
  | 'mehendi_artist'
  | 'makeup_artist'
  | 'dj'
  | 'band'
  | 'florist'
  | 'pandit'
  | 'tent_house'
  | 'lighting'
  | 'invitation'
  | 'jeweller'
  | 'choreographer'
  | 'transportation'
  | 'other';

// ---------------------------------------------------------------------------
// Database interface
// ---------------------------------------------------------------------------

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          password_hash: string;
          name: string;
          slug: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          password_hash: string;
          name: string;
          slug?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          password_hash?: string;
          name?: string;
          slug?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };

      venues: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          venue_type: string | null;
          address: string;
          city: string;
          google_maps_link: string | null;
          contact_person: string | null;
          contact_phone: string | null;
          capacity: number | null;
          total_cost: number | null;
          has_accommodation: boolean;
          default_check_in_date: string | null;
          default_check_out_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          venue_type?: string | null;
          address: string;
          city: string;
          google_maps_link?: string | null;
          contact_person?: string | null;
          contact_phone?: string | null;
          capacity?: number | null;
          total_cost?: number | null;
          has_accommodation?: boolean;
          default_check_in_date?: string | null;
          default_check_out_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          venue_type?: string | null;
          address?: string;
          city?: string;
          google_maps_link?: string | null;
          contact_person?: string | null;
          contact_phone?: string | null;
          capacity?: number | null;
          total_cost?: number | null;
          has_accommodation?: boolean;
          default_check_in_date?: string | null;
          default_check_out_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'venues_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      events: {
        Row: {
          id: string;
          name: string;
          event_type: string;
          description: string | null;
          event_date: string;
          start_time: string;
          end_time: string | null;
          venue_id: string | null;
          dress_code: string | null;
          theme: string | null;
          color_palette: Json | null;
          estimated_guests: number | null;
          is_public: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          event_type: string;
          description?: string | null;
          event_date: string;
          start_time: string;
          end_time?: string | null;
          venue_id?: string | null;
          dress_code?: string | null;
          theme?: string | null;
          color_palette?: Json | null;
          estimated_guests?: number | null;
          is_public?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          event_type?: string;
          description?: string | null;
          event_date?: string;
          start_time?: string;
          end_time?: string | null;
          venue_id?: string | null;
          dress_code?: string | null;
          theme?: string | null;
          color_palette?: Json | null;
          estimated_guests?: number | null;
          is_public?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'events_venue_id_fkey';
            columns: ['venue_id'];
            isOneToOne: false;
            referencedRelation: 'venues';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'events_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      guest_groups: {
        Row: {
          id: string;
          name: string;
          side: DbGuestSide;
          description: string | null;
          primary_contact_id: string | null;
          created_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          side: DbGuestSide;
          description?: string | null;
          primary_contact_id?: string | null;
          created_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          side?: DbGuestSide;
          description?: string | null;
          primary_contact_id?: string | null;
          created_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'guest_groups_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      guests: {
        Row: {
          id: string;
          group_id: string | null;
          first_name: string;
          last_name: string | null;
          phone: string | null;
          email: string | null;
          side: DbGuestSide;
          relationship: string | null;
          is_vip: boolean;
          age_group: DbAgeGroup;
          meal_preference: DbMealPreference;
          dietary_restrictions: string | null;
          needs_accommodation: boolean;
          needs_pickup: boolean;
          arrival_date: string | null;
          arrival_time: string | null;
          departure_date: string | null;
          departure_time: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          group_id?: string | null;
          first_name: string;
          last_name?: string | null;
          phone?: string | null;
          email?: string | null;
          side: DbGuestSide;
          relationship?: string | null;
          is_vip?: boolean;
          age_group?: DbAgeGroup;
          meal_preference?: DbMealPreference;
          dietary_restrictions?: string | null;
          needs_accommodation?: boolean;
          needs_pickup?: boolean;
          arrival_date?: string | null;
          arrival_time?: string | null;
          departure_date?: string | null;
          departure_time?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          group_id?: string | null;
          first_name?: string;
          last_name?: string | null;
          phone?: string | null;
          email?: string | null;
          side?: DbGuestSide;
          relationship?: string | null;
          is_vip?: boolean;
          age_group?: DbAgeGroup;
          meal_preference?: DbMealPreference;
          dietary_restrictions?: string | null;
          needs_accommodation?: boolean;
          needs_pickup?: boolean;
          arrival_date?: string | null;
          arrival_time?: string | null;
          departure_date?: string | null;
          departure_time?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'guests_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'guest_groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'guests_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      guest_event_rsvp: {
        Row: {
          id: string;
          guest_id: string;
          event_id: string;
          rsvp_status: DbRsvpStatus;
          responded_at: string | null;
          plus_ones: number;
          plus_one_names: string[] | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          guest_id: string;
          event_id: string;
          rsvp_status?: DbRsvpStatus;
          responded_at?: string | null;
          plus_ones?: number;
          plus_one_names?: string[] | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          guest_id?: string;
          event_id?: string;
          rsvp_status?: DbRsvpStatus;
          responded_at?: string | null;
          plus_ones?: number;
          plus_one_names?: string[] | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'guest_event_rsvp_guest_id_fkey';
            columns: ['guest_id'];
            isOneToOne: false;
            referencedRelation: 'guests';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'guest_event_rsvp_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
        ];
      };

      rooms: {
        Row: {
          id: string;
          venue_id: string;
          room_number: string;
          room_type: DbRoomType;
          capacity: number;
          rate_per_night: number | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          venue_id: string;
          room_number: string;
          room_type: DbRoomType;
          capacity?: number;
          rate_per_night?: number | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          venue_id?: string;
          room_number?: string;
          room_type?: DbRoomType;
          capacity?: number;
          rate_per_night?: number | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'rooms_venue_id_fkey';
            columns: ['venue_id'];
            isOneToOne: false;
            referencedRelation: 'venues';
            referencedColumns: ['id'];
          },
        ];
      };

      room_allocations: {
        Row: {
          id: string;
          room_id: string;
          guest_ids: string[];
          check_in_date: string;
          check_out_date: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          guest_ids: string[];
          check_in_date: string;
          check_out_date: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          guest_ids?: string[];
          check_in_date?: string;
          check_out_date?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'room_allocations_room_id_fkey';
            columns: ['room_id'];
            isOneToOne: false;
            referencedRelation: 'rooms';
            referencedColumns: ['id'];
          },
        ];
      };

      vendors: {
        Row: {
          id: string;
          name: string;
          category: DbVendorCategory;
          contact_person: string | null;
          phone: string | null;
          email: string | null;
          total_cost: number | null;
          side: DbGuestSide | null;
          is_shared: boolean;
          is_confirmed: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: DbVendorCategory;
          contact_person?: string | null;
          phone?: string | null;
          email?: string | null;
          total_cost?: number | null;
          side?: DbGuestSide | null;
          is_shared?: boolean;
          is_confirmed?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: DbVendorCategory;
          contact_person?: string | null;
          phone?: string | null;
          email?: string | null;
          total_cost?: number | null;
          side?: DbGuestSide | null;
          is_shared?: boolean;
          is_confirmed?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'vendors_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      vendor_event_assignments: {
        Row: {
          id: string;
          vendor_id: string;
          event_id: string;
          service_description: string | null;
          arrival_time: string | null;
          setup_requirements: string | null;
          special_instructions: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          vendor_id: string;
          event_id: string;
          service_description?: string | null;
          arrival_time?: string | null;
          setup_requirements?: string | null;
          special_instructions?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          vendor_id?: string;
          event_id?: string;
          service_description?: string | null;
          arrival_time?: string | null;
          setup_requirements?: string | null;
          special_instructions?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'vendor_event_assignments_vendor_id_fkey';
            columns: ['vendor_id'];
            isOneToOne: false;
            referencedRelation: 'vendors';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'vendor_event_assignments_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
        ];
      };

      expense_categories: {
        Row: {
          id: string;
          name: string;
          parent_category_id: string | null;
          allocated_amount: number;
          description: string | null;
          display_order: number;
          created_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          parent_category_id?: string | null;
          allocated_amount?: number;
          description?: string | null;
          display_order?: number;
          created_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          parent_category_id?: string | null;
          allocated_amount?: number;
          description?: string | null;
          display_order?: number;
          created_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'expense_categories_parent_category_id_fkey';
            columns: ['parent_category_id'];
            isOneToOne: false;
            referencedRelation: 'expense_categories';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expense_categories_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      expenses: {
        Row: {
          id: string;
          category_id: string | null;
          vendor_id: string | null;
          event_id: string | null;
          description: string;
          amount: number;
          expense_date: string;
          receipt_url: string | null;
          paid_by: string | null;
          side: DbGuestSide | null;
          is_shared: boolean;
          share_percentage: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          category_id?: string | null;
          vendor_id?: string | null;
          event_id?: string | null;
          description: string;
          amount: number;
          expense_date: string;
          receipt_url?: string | null;
          paid_by?: string | null;
          side?: DbGuestSide | null;
          is_shared?: boolean;
          share_percentage?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          category_id?: string | null;
          vendor_id?: string | null;
          event_id?: string | null;
          description?: string;
          amount?: number;
          expense_date?: string;
          receipt_url?: string | null;
          paid_by?: string | null;
          side?: DbGuestSide | null;
          is_shared?: boolean;
          share_percentage?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'expenses_category_id_fkey';
            columns: ['category_id'];
            isOneToOne: false;
            referencedRelation: 'expense_categories';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expenses_vendor_id_fkey';
            columns: ['vendor_id'];
            isOneToOne: false;
            referencedRelation: 'vendors';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expenses_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expenses_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      payments: {
        Row: {
          id: string;
          user_id: string | null;
          venue_id: string | null;
          vendor_id: string | null;
          amount: number;
          payment_date: string;
          payment_method: DbPaymentMethod;
          side: DbGuestSide | null;
          transaction_reference: string | null;
          notes: string | null;
          is_planned: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          venue_id?: string | null;
          vendor_id?: string | null;
          amount: number;
          payment_date: string;
          payment_method: DbPaymentMethod;
          side?: DbGuestSide | null;
          transaction_reference?: string | null;
          notes?: string | null;
          is_planned?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          venue_id?: string | null;
          vendor_id?: string | null;
          amount?: number;
          payment_date?: string;
          payment_method?: DbPaymentMethod;
          side?: DbGuestSide | null;
          transaction_reference?: string | null;
          notes?: string | null;
          is_planned?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'payments_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'payments_vendor_id_fkey';
            columns: ['vendor_id'];
            isOneToOne: false;
            referencedRelation: 'vendors';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'payments_venue_id_fkey';
            columns: ['venue_id'];
            isOneToOne: false;
            referencedRelation: 'venues';
            referencedColumns: ['id'];
          },
        ];
      };

      expense_summary: {
        Row: {
          id: string;
          total_expense: number;
          bride_side_contribution: number;
          groom_side_contribution: number;
          currency: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          total_expense?: number;
          bride_side_contribution?: number;
          groom_side_contribution?: number;
          currency?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          total_expense?: number;
          bride_side_contribution?: number;
          groom_side_contribution?: number;
          currency?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'expense_summary_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      tasks: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          event_id: string | null;
          assigned_to: string | null;
          priority: DbTaskPriority;
          status: DbTaskStatus;
          due_date: string | null;
          completed_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          event_id?: string | null;
          assigned_to?: string | null;
          priority?: DbTaskPriority;
          status?: DbTaskStatus;
          due_date?: string | null;
          completed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          event_id?: string | null;
          assigned_to?: string | null;
          priority?: DbTaskPriority;
          status?: DbTaskStatus;
          due_date?: string | null;
          completed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'tasks_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'tasks_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };

      website_content: {
        Row: {
          id: string;
          section_name: string;
          content: Json;
          is_visible: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          section_name: string;
          content: Json;
          is_visible?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          section_name?: string;
          content?: Json;
          is_visible?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'website_content_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
    };

    Views: {
      [_ in never]: never;
    };

    Functions: {
      [_ in never]: never;
    };

    Enums: {
      guest_side: DbGuestSide;
      rsvp_status: DbRsvpStatus;
      meal_preference: DbMealPreference;
      age_group: DbAgeGroup;
      payment_method: DbPaymentMethod;
      task_priority: DbTaskPriority;
      task_status: DbTaskStatus;
      room_type: DbRoomType;
      vendor_category: DbVendorCategory;
    };

    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// ---------------------------------------------------------------------------
// Convenience row/insert/update type helpers
// ---------------------------------------------------------------------------

type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T];

export type TableRow<T extends keyof Database['public']['Tables']> = Tables<T>['Row'];

export type TableInsert<T extends keyof Database['public']['Tables']> = Tables<T>['Insert'];

export type TableUpdate<T extends keyof Database['public']['Tables']> = Tables<T>['Update'];
