// Auto-generated Supabase types — hand-crafted to match migration schema.
// Do not edit this file directly; regenerate from migrations instead.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ---------------------------------------------------------------------------
// DB Enums
// ---------------------------------------------------------------------------

export type DbGuestSide = "bride" | "groom" | "mutual";
export type DbRsvpStatus = "pending" | "confirmed" | "declined" | "tentative";
export type DbMealPreference =
  | "vegetarian"
  | "jain"
  | "vegan"
  | "non_vegetarian";
export type DbAgeGroup = "child" | "adult" | "senior";
export type DbGender = "male" | "female" | "other";
export type DbPaymentStatus =
  | "pending"
  | "partial"
  | "paid"
  | "overdue"
  | "cancelled";
export type DbPaymentMethod =
  | "cash"
  | "bank_transfer"
  | "upi"
  | "cheque"
  | "credit_card";
export type DbTaskPriority = "low" | "medium" | "high" | "urgent";
export type DbTaskStatus = "pending" | "in_progress" | "completed" | "cancelled";
export type DbRoomType = "single" | "double" | "suite" | "family" | "dormitory";
export type DbVendorCategory =
  | "caterer"
  | "decorator"
  | "photographer"
  | "videographer"
  | "mehendi_artist"
  | "makeup_artist"
  | "dj"
  | "band"
  | "florist"
  | "pandit"
  | "tent_house"
  | "lighting"
  | "invitation"
  | "jeweller"
  | "choreographer"
  | "transportation"
  | "other";

// ---------------------------------------------------------------------------
// Database interface
// ---------------------------------------------------------------------------

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          password_hash: string;
          name: string;
          role: "admin" | "family" | "friends";
          slug: string | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          password_hash: string;
          name: string;
          role: "admin" | "family" | "friends";
          slug?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          password_hash?: string;
          name?: string;
          role?: "admin" | "family" | "friends";
          slug?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "users_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      venues: {
        Row: {
          id: string;
          name: string;
          venue_type: string | null;
          address: string;
          city: string;
          state: string | null;
          pincode: string | null;
          google_maps_link: string | null;
          latitude: number | null;
          longitude: number | null;
          contact_person: string | null;
          contact_phone: string | null;
          contact_email: string | null;
          capacity: number | null;
          parking_capacity: number | null;
          amenities: Json | null;
          restrictions: string | null;
          photos: string[] | null;
          documents: string[] | null;
          booking_amount: number | null;
          total_cost: number | null;
          payment_status: DbPaymentStatus | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          venue_type?: string | null;
          address: string;
          city: string;
          state?: string | null;
          pincode?: string | null;
          google_maps_link?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          contact_person?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          capacity?: number | null;
          parking_capacity?: number | null;
          amenities?: Json | null;
          restrictions?: string | null;
          photos?: string[] | null;
          documents?: string[] | null;
          booking_amount?: number | null;
          total_cost?: number | null;
          payment_status?: DbPaymentStatus | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          venue_type?: string | null;
          address?: string;
          city?: string;
          state?: string | null;
          pincode?: string | null;
          google_maps_link?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          contact_person?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          capacity?: number | null;
          parking_capacity?: number | null;
          amenities?: Json | null;
          restrictions?: string | null;
          photos?: string[] | null;
          documents?: string[] | null;
          booking_amount?: number | null;
          total_cost?: number | null;
          payment_status?: DbPaymentStatus | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "venues_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      events: {
        Row: {
          id: string;
          name: string;
          event_type: string;
          description: string | null;
          event_date: string;
          start_time: string;
          end_time: string | null;
          venue_id: string | null;
          dress_code: string | null;
          theme: string | null;
          color_palette: Json | null;
          rituals: Json | null;
          special_notes: string | null;
          estimated_guests: number | null;
          is_public: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          event_type: string;
          description?: string | null;
          event_date: string;
          start_time: string;
          end_time?: string | null;
          venue_id?: string | null;
          dress_code?: string | null;
          theme?: string | null;
          color_palette?: Json | null;
          rituals?: Json | null;
          special_notes?: string | null;
          estimated_guests?: number | null;
          is_public?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          event_type?: string;
          description?: string | null;
          event_date?: string;
          start_time?: string;
          end_time?: string | null;
          venue_id?: string | null;
          dress_code?: string | null;
          theme?: string | null;
          color_palette?: Json | null;
          rituals?: Json | null;
          special_notes?: string | null;
          estimated_guests?: number | null;
          is_public?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "events_venue_id_fkey";
            columns: ["venue_id"];
            isOneToOne: false;
            referencedRelation: "venues";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      guest_groups: {
        Row: {
          id: string;
          name: string;
          side: DbGuestSide;
          description: string | null;
          primary_contact_id: string | null;
          created_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          side: DbGuestSide;
          description?: string | null;
          primary_contact_id?: string | null;
          created_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          side?: DbGuestSide;
          description?: string | null;
          primary_contact_id?: string | null;
          created_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "guest_groups_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      guests: {
        Row: {
          id: string;
          group_id: string | null;
          first_name: string;
          last_name: string | null;
          phone: string | null;
          email: string | null;
          side: DbGuestSide;
          relationship: string | null;
          is_vip: boolean;
          age_group: DbAgeGroup;
          gender: DbGender | null;
          meal_preference: DbMealPreference;
          dietary_restrictions: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          country: string;
          needs_accommodation: boolean;
          needs_pickup: boolean;
          pickup_location: string | null;
          arrival_date: string | null;
          arrival_time: string | null;
          departure_date: string | null;
          departure_time: string | null;
          transport_mode: string | null;
          transport_details: string | null;
          special_requirements: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          group_id?: string | null;
          first_name: string;
          last_name?: string | null;
          phone?: string | null;
          email?: string | null;
          side: DbGuestSide;
          relationship?: string | null;
          is_vip?: boolean;
          age_group?: DbAgeGroup;
          gender?: DbGender | null;
          meal_preference?: DbMealPreference;
          dietary_restrictions?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          needs_accommodation?: boolean;
          needs_pickup?: boolean;
          pickup_location?: string | null;
          arrival_date?: string | null;
          arrival_time?: string | null;
          departure_date?: string | null;
          departure_time?: string | null;
          transport_mode?: string | null;
          transport_details?: string | null;
          special_requirements?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          group_id?: string | null;
          first_name?: string;
          last_name?: string | null;
          phone?: string | null;
          email?: string | null;
          side?: DbGuestSide;
          relationship?: string | null;
          is_vip?: boolean;
          age_group?: DbAgeGroup;
          gender?: DbGender | null;
          meal_preference?: DbMealPreference;
          dietary_restrictions?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          needs_accommodation?: boolean;
          needs_pickup?: boolean;
          pickup_location?: string | null;
          arrival_date?: string | null;
          arrival_time?: string | null;
          departure_date?: string | null;
          departure_time?: string | null;
          transport_mode?: string | null;
          transport_details?: string | null;
          special_requirements?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "guests_group_id_fkey";
            columns: ["group_id"];
            isOneToOne: false;
            referencedRelation: "guest_groups";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "guests_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      guest_event_rsvp: {
        Row: {
          id: string;
          guest_id: string;
          event_id: string;
          rsvp_status: DbRsvpStatus;
          responded_at: string | null;
          plus_ones: number;
          plus_one_names: string[] | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          guest_id: string;
          event_id: string;
          rsvp_status?: DbRsvpStatus;
          responded_at?: string | null;
          plus_ones?: number;
          plus_one_names?: string[] | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          guest_id?: string;
          event_id?: string;
          rsvp_status?: DbRsvpStatus;
          responded_at?: string | null;
          plus_ones?: number;
          plus_one_names?: string[] | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "guest_event_rsvp_guest_id_fkey";
            columns: ["guest_id"];
            isOneToOne: false;
            referencedRelation: "guests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "guest_event_rsvp_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
        ];
      };

      accommodations: {
        Row: {
          id: string;
          name: string;
          accommodation_type: string | null;
          address: string | null;
          city: string | null;
          distance_from_venue: string | null;
          google_maps_link: string | null;
          contact_person: string | null;
          contact_phone: string | null;
          contact_email: string | null;
          check_in_time: string | null;
          check_out_time: string | null;
          amenities: Json | null;
          photos: string[] | null;
          booking_reference: string | null;
          total_rooms_booked: number | null;
          booking_amount: number | null;
          total_cost: number | null;
          payment_status: DbPaymentStatus | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          accommodation_type?: string | null;
          address?: string | null;
          city?: string | null;
          distance_from_venue?: string | null;
          google_maps_link?: string | null;
          contact_person?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          check_in_time?: string | null;
          check_out_time?: string | null;
          amenities?: Json | null;
          photos?: string[] | null;
          booking_reference?: string | null;
          total_rooms_booked?: number | null;
          booking_amount?: number | null;
          total_cost?: number | null;
          payment_status?: DbPaymentStatus | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          accommodation_type?: string | null;
          address?: string | null;
          city?: string | null;
          distance_from_venue?: string | null;
          google_maps_link?: string | null;
          contact_person?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          check_in_time?: string | null;
          check_out_time?: string | null;
          amenities?: Json | null;
          photos?: string[] | null;
          booking_reference?: string | null;
          total_rooms_booked?: number | null;
          booking_amount?: number | null;
          total_cost?: number | null;
          payment_status?: DbPaymentStatus | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "accommodations_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      rooms: {
        Row: {
          id: string;
          accommodation_id: string;
          room_number: string;
          room_type: DbRoomType;
          floor: string | null;
          capacity: number;
          has_ac: boolean;
          has_attached_bath: boolean;
          rate_per_night: number | null;
          is_accessible: boolean;
          amenities: Json | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          accommodation_id: string;
          room_number: string;
          room_type: DbRoomType;
          floor?: string | null;
          capacity?: number;
          has_ac?: boolean;
          has_attached_bath?: boolean;
          rate_per_night?: number | null;
          is_accessible?: boolean;
          amenities?: Json | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          accommodation_id?: string;
          room_number?: string;
          room_type?: DbRoomType;
          floor?: string | null;
          capacity?: number;
          has_ac?: boolean;
          has_attached_bath?: boolean;
          rate_per_night?: number | null;
          is_accessible?: boolean;
          amenities?: Json | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "rooms_accommodation_id_fkey";
            columns: ["accommodation_id"];
            isOneToOne: false;
            referencedRelation: "accommodations";
            referencedColumns: ["id"];
          },
        ];
      };

      room_allocations: {
        Row: {
          id: string;
          room_id: string;
          guest_id: string;
          check_in_date: string;
          check_out_date: string;
          is_primary_guest: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          guest_id: string;
          check_in_date: string;
          check_out_date: string;
          is_primary_guest?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          guest_id?: string;
          check_in_date?: string;
          check_out_date?: string;
          is_primary_guest?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "room_allocations_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "rooms";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "room_allocations_guest_id_fkey";
            columns: ["guest_id"];
            isOneToOne: false;
            referencedRelation: "guests";
            referencedColumns: ["id"];
          },
        ];
      };

      vendors: {
        Row: {
          id: string;
          name: string;
          category: DbVendorCategory;
          subcategory: string | null;
          company_name: string | null;
          contact_person: string | null;
          phone: string | null;
          alternate_phone: string | null;
          email: string | null;
          website: string | null;
          instagram_handle: string | null;
          address: string | null;
          city: string | null;
          description: string | null;
          services_offered: string[] | null;
          portfolio_links: string[] | null;
          photos: string[] | null;
          rating: number | null;
          is_confirmed: boolean;
          contract_signed: boolean;
          contract_document: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: DbVendorCategory;
          subcategory?: string | null;
          company_name?: string | null;
          contact_person?: string | null;
          phone?: string | null;
          alternate_phone?: string | null;
          email?: string | null;
          website?: string | null;
          instagram_handle?: string | null;
          address?: string | null;
          city?: string | null;
          description?: string | null;
          services_offered?: string[] | null;
          portfolio_links?: string[] | null;
          photos?: string[] | null;
          rating?: number | null;
          is_confirmed?: boolean;
          contract_signed?: boolean;
          contract_document?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: DbVendorCategory;
          subcategory?: string | null;
          company_name?: string | null;
          contact_person?: string | null;
          phone?: string | null;
          alternate_phone?: string | null;
          email?: string | null;
          website?: string | null;
          instagram_handle?: string | null;
          address?: string | null;
          city?: string | null;
          description?: string | null;
          services_offered?: string[] | null;
          portfolio_links?: string[] | null;
          photos?: string[] | null;
          rating?: number | null;
          is_confirmed?: boolean;
          contract_signed?: boolean;
          contract_document?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "vendors_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      budget_categories: {
        Row: {
          id: string;
          name: string;
          parent_category_id: string | null;
          allocated_amount: number;
          description: string | null;
          display_order: number;
          created_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          name: string;
          parent_category_id?: string | null;
          allocated_amount?: number;
          description?: string | null;
          display_order?: number;
          created_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          name?: string;
          parent_category_id?: string | null;
          allocated_amount?: number;
          description?: string | null;
          display_order?: number;
          created_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "budget_categories_parent_category_id_fkey";
            columns: ["parent_category_id"];
            isOneToOne: false;
            referencedRelation: "budget_categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "budget_categories_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      expenses: {
        Row: {
          id: string;
          category_id: string | null;
          vendor_id: string | null;
          event_id: string | null;
          description: string;
          amount: number;
          expense_date: string;
          receipt_url: string | null;
          paid_by: string | null;
          side: DbGuestSide | null;
          is_shared: boolean;
          share_percentage: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          category_id?: string | null;
          vendor_id?: string | null;
          event_id?: string | null;
          description: string;
          amount: number;
          expense_date: string;
          receipt_url?: string | null;
          paid_by?: string | null;
          side?: DbGuestSide | null;
          is_shared?: boolean;
          share_percentage?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          category_id?: string | null;
          vendor_id?: string | null;
          event_id?: string | null;
          description?: string;
          amount?: number;
          expense_date?: string;
          receipt_url?: string | null;
          paid_by?: string | null;
          side?: DbGuestSide | null;
          is_shared?: boolean;
          share_percentage?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "expenses_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "budget_categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "expenses_vendor_id_fkey";
            columns: ["vendor_id"];
            isOneToOne: false;
            referencedRelation: "vendors";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "expenses_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "expenses_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      payments: {
        Row: {
          id: string;
          expense_id: string | null;
          vendor_id: string | null;
          accommodation_id: string | null;
          venue_id: string | null;
          amount: number;
          payment_date: string;
          payment_method: DbPaymentMethod;
          transaction_reference: string | null;
          paid_by: string | null;
          received_by: string | null;
          receipt_url: string | null;
          status: DbPaymentStatus;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          expense_id?: string | null;
          vendor_id?: string | null;
          accommodation_id?: string | null;
          venue_id?: string | null;
          amount: number;
          payment_date: string;
          payment_method: DbPaymentMethod;
          transaction_reference?: string | null;
          paid_by?: string | null;
          received_by?: string | null;
          receipt_url?: string | null;
          status?: DbPaymentStatus;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          expense_id?: string | null;
          vendor_id?: string | null;
          accommodation_id?: string | null;
          venue_id?: string | null;
          amount?: number;
          payment_date?: string;
          payment_method?: DbPaymentMethod;
          transaction_reference?: string | null;
          paid_by?: string | null;
          received_by?: string | null;
          receipt_url?: string | null;
          status?: DbPaymentStatus;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_expense_id_fkey";
            columns: ["expense_id"];
            isOneToOne: false;
            referencedRelation: "expenses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_vendor_id_fkey";
            columns: ["vendor_id"];
            isOneToOne: false;
            referencedRelation: "vendors";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_accommodation_id_fkey";
            columns: ["accommodation_id"];
            isOneToOne: false;
            referencedRelation: "accommodations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_venue_id_fkey";
            columns: ["venue_id"];
            isOneToOne: false;
            referencedRelation: "venues";
            referencedColumns: ["id"];
          },
        ];
      };

      budget_summary: {
        Row: {
          id: string;
          total_budget: number;
          bride_side_contribution: number;
          groom_side_contribution: number;
          currency: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          total_budget?: number;
          bride_side_contribution?: number;
          groom_side_contribution?: number;
          currency?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          total_budget?: number;
          bride_side_contribution?: number;
          groom_side_contribution?: number;
          currency?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "budget_summary_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      tasks: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          category: string | null;
          event_id: string | null;
          assigned_to: string | null;
          assigned_side: DbGuestSide | null;
          priority: DbTaskPriority;
          status: DbTaskStatus;
          due_date: string | null;
          completed_at: string | null;
          reminder_date: string | null;
          parent_task_id: string | null;
          display_order: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          category?: string | null;
          event_id?: string | null;
          assigned_to?: string | null;
          assigned_side?: DbGuestSide | null;
          priority?: DbTaskPriority;
          status?: DbTaskStatus;
          due_date?: string | null;
          completed_at?: string | null;
          reminder_date?: string | null;
          parent_task_id?: string | null;
          display_order?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          category?: string | null;
          event_id?: string | null;
          assigned_to?: string | null;
          assigned_side?: DbGuestSide | null;
          priority?: DbTaskPriority;
          status?: DbTaskStatus;
          due_date?: string | null;
          completed_at?: string | null;
          reminder_date?: string | null;
          parent_task_id?: string | null;
          display_order?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_parent_task_id_fkey";
            columns: ["parent_task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };

      website_content: {
        Row: {
          id: string;
          section_name: string;
          content: Json;
          is_visible: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          section_name: string;
          content: Json;
          is_visible?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          id?: string;
          section_name?: string;
          content?: Json;
          is_visible?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "website_content_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
    };

    Views: {
      [_ in never]: never;
    };

    Functions: {
      [_ in never]: never;
    };

    Enums: {
      guest_side: DbGuestSide;
      rsvp_status: DbRsvpStatus;
      meal_preference: DbMealPreference;
      age_group: DbAgeGroup;
      gender: DbGender;
      payment_status: DbPaymentStatus;
      payment_method: DbPaymentMethod;
      task_priority: DbTaskPriority;
      task_status: DbTaskStatus;
      room_type: DbRoomType;
      vendor_category: DbVendorCategory;
    };

    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// ---------------------------------------------------------------------------
// Convenience row/insert/update type helpers
// ---------------------------------------------------------------------------

type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T];

export type TableRow<T extends keyof Database["public"]["Tables"]> =
  Tables<T>["Row"];

export type TableInsert<T extends keyof Database["public"]["Tables"]> =
  Tables<T>["Insert"];

export type TableUpdate<T extends keyof Database["public"]["Tables"]> =
  Tables<T>["Update"];
